'\" t
.\"     Title: ffind
.\"    Author: David Gamba, davidgamba at gmail.com
.\" Generator: Asciidoctor 1.5.5
.\"      Date: 2017-07-23
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "FFIND" "1" "2017-07-23" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.LINKSTYLE blue R < >
.SH "NAME"
ffind \- Fast Regex Find, faster common Find searches using the power of Golang’s Regex engine
.SH "SYNOPSIS"
.sp
# List all files under current dir
.RS 4
\fBffind\fP [\(aqOPTIONS\(aq...]
.RE
.sp
# List file_pattern matching files under current dir, # <file_pattern> can\(cqt end in /
.RS 4
\fBffind\fP \(aqfile_pattern\(aq [\(aqOPTIONS\(aq...]
.RE
.sp
# List file pattern matching files under given dir
.RS 4
\fBffind\fP \(aqfile_pattern\(aq \(aqdir\(aq [\(aqOPTIONS\(aq...]
.RE
.sp
# List all files under given dir
.RS 4
\fBffind\fP \(aqdir/\(aq [\(aqOPTIONS\(aq...]
.RE
.sp
# List file pattern matching files under given dir
.RS 4
\fBffind\fP \(aqdir/\(aq \(aqfile_pattern\(aq [\(aqOPTIONS\(aq...]
.RE
.sp
# OPTIONS
.RS 4
[\fB\-c\fP|\fB\-\-case\fP]
.sp
[\fB\-t\fP|\fB\-\-type\fP \(aqf|d|filetype\(aq]...
.sp
[\fB\-T\fP|\fB\-\-no\-type\fP \(aqfiletype\(aq]...
.sp
[\fB\-e\fP|\fB\-\-extension\fP \(aqextensionToMatch\(aq]...
.sp
[\fB\-E\fP|\fB\-\-no\-extension\fP \(aqextensionToIgnore\(aq]...
.sp
[\fB\-\-no\-follow\fP]
.sp
[\fB\-\-abs\fP|\fB\-\-abs\-path\fP]
.sp
[\fB\-\-num\-sort\fP]
.sp
[\fB\-\-hidden\fP]
.sp
[\fB\-\-vcs\fP] # Sets \-\-hidden when set
.sp
[\fB\-\-verbose\fP]
.RE
.sp
# Show type list
.RS 4
\fBffind\fP \fB\-\-type\-list\fP|\fB\-\-typelist\fP
.RE
.sp
# Show version number
.RS 4
\fBffind\fP \fB\-\-version\fP
.RE
.sp
# Show short help
.RS 4
\fBffind\fP \fB\-h\fP|\fB\-?\fP|\fB\-\-help\fP
.RE
.SS "TODO"
.sp
[\fB\-\-color\fP \(aqnever\(aq|\(aqauto\(aq|\(aqalways\(aq]
.SH "DESCRIPTION"
.sp
This command focuses on the most common find searches.
They are optimized for typing speed as not to interrupt your thought process.
.sp
Instead of typing "find . \-iname \(rs\(aq*pattern*\(rs\(aq" or "find \-regextype some_type \-regex \(rs\(aq^.*?pattern.*$\(aq" you can simply type "ffind pattern".
.sp
More obscure searches are probably better suited to find, but you have to deal with that syntax so...
.sp
This command is also only intended to search for files, once you find them, pipe the output if you want to execute a command on them.
.SH "OPTIONS"
.sp
\(aqdir\(aq
.RS 4
Directory to search from.
Defaults to current working directory.
.RE
.sp
\(aqfile_pattern\(aq
.RS 4
Pattern to search for (In regex syntax).
Use single quotes to avoid shell expansion.
.RE
.sp
\fB\-c\fP|\fB\-\-case\fP
.RS 4
Match case sensitive.
Default is to match case insensitive.
.RE
.sp
\fB\-t\fP|\fB\-\-type\fP \(aqf\(aq|\(aqd\(aq|\(aqfiletype\(aq
.RS 4
Show only results of given type.
\(aqf\(aq for file and \(aqd\(aq for dir or any of the \fB\-\-type\-list\fP types.
.RE
.sp
\fB\-T\fP|\fB\-\-no\-type\fP filetype\(aq
.RS 4
Skip results of given type from any of the \fB\-\-type\-list\fP types.
.RE
.sp
\fB\-e\fP|\fB\-\-extension\fP \(aqextensionToMatch\(aq
.RS 4
Include file results that end in the given \(aqextension\(aq.
.RE
.sp
\fB\-E\fP|\fB\-\-no\-extension\fP \(aqextensionToIgnore\(aq
.RS 4
Exclude file results that end in the given \(aqextension\(aq.
.RE
.sp
\fB\-\-no\-follow\fP
.RS 4
Do not follow symlinks.
Avoid infinite recursion.
.RE
.sp
\fB\-\-abs\fP|\fB\-\-abs\-path\fP
.RS 4
Print absolute path to file.
Defaults to printing relative path.
.RE
.sp
\fB\-\-num\-sort\fP
.RS 4
When there are directories that fully match a number, sort them numerically.
.RE
.sp
\fB\-\-hidden\fP
.RS 4
Show hidden files (starting with dot ".").
.RE
.sp
\fB\-\-vcs\fP
.RS 4
Do not ignore git, subversion or mercurial directories.
.RE
.sp
\fB\-\-verbose\fP
.RS 4
Show options in effect.
.RE
.sp
\fB\-\-type\-list\fP|\fB\-\-typelist\fP
.RS 4
Show type list keys and matching patterns.
.RE
.sp
\fB\-\-version\fP
.RS 4
Show version.
.RE
.sp
\fB\-h\fP|\fB\-?\fP|\fB\-\-help\fP
.RS 4
Show short help.
.RE
.SS "TODO"
.sp
\fB\-\-color\fP \(aqnever\(aq|\(aqauto\(aq|\(aqalways\(aq
.RS 4
Select color use: \(aqnever\(aq, \(aqauto\(aq (default), \(aqalways\(aq.
.RE
.SH "EXAMPLES"
.sp
Search for a file or directory with the word info in its name
.RS 4
ffind info
.RE
.sp
Search for a file with the word info in its filename
.RS 4
ffind info \-t f
.RE
.sp
Search for a directory with the word info in its dirname
.RS 4
ffind info \-t d
.RE
.sp
Search in your home dir for a file or directory with the word info in its name
.RS 4
ffind info \(aq~\(aq
.RE
.SH "ROADMAP"
.sp
Limit depth option
.RS 4
Might need to add this for large projects.
.RE
.sp
Parallel execution
.RS 4
Will not return sorted results but will speed up response.
.RE
.sp
Version Sort
.RS 4
Only numerical sort is implemented (the whole filename is a number).
Look into providing version sort for filenames.
.RE
.SH "VERSION"
.sp
0.4
.SH "SOURCE CODE"
.sp
github: \c
.URL "https://github.com/DavidGamba/ffind" "" ""
.SH "LICENSE"
.sp
This file is part of ffind.
.sp
Copyright \(co 2017  David Gamba Rios
.sp
This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at \c
.URL "http://mozilla.org/MPL/2.0/" "" "."
.SH "AUTHOR(S)"
.sp
\fBDavid Gamba, davidgamba at gmail.com\fP
.RS 4
Author(s).
.RE